name: Deploy to Production Env

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'git-tag'
        required: true
        default: 'master'

env:
  project-directory: ./

jobs:
  deploy-production:
    name: Deploy latest to production environment, requires approval
    runs-on: ubuntu-latest
    if: |
      github.repository == 'Greenstand/treetracker-wallet-api'
    steps:
      - uses: actions/checkout@v2

      - name: Install kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

      - name: Run kustomize
        run: (cd deployment/overlays/production && ../../../kustomize edit set image greenstand/treetracker-wallet-api:${{ github.event.inputs.environment }})

      - name: Commit production kustomization file with new app version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "chore: bump docker image tag ${{ github.event.inputs.environment }} [skip ci]"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
